catalystneuro/buffalo_db

.github/workflows/test.yml

This change add a github action for testing automatically each commit. It depends on db env var support added in this commit:
https://github.com/catalystneuro/alyx/pull/7/commits/51d861f7d1a01ac666d7c5f5ab8562dcb776ec69

Added github action for testing

---

alyx/alyx/urls.py
alyx/buffalo/admin.py
alyx/buffalo/forms.py
alyx/buffalo/models.py
alyx/buffalo/utils.py
alyx/buffalo/views.py
alyx/templates/buffalo/electrode_bulk_load.html
requirements.txt

This includes form for electrodes bulk load

Electrodes map file

---

requirements.txt

Added scipy package to requirements.txt

Added scipy package

---

alyx/buffalo/models.py
alyx/buffalo/views.py

Fix electrode default values problems

Fix electrode default values

---

alyx/buffalo/admin.py
alyx/buffalo/utils.py
alyx/templates/buffalo/admin_session_details.html
alyx/templates/buffalo/admin_subject_details.html

This includes:
* Improved queries electrodelog
* Added  shortcut buttons to electrodelog

Improve queries electrodelog and buttons

---

alyx/buffalo/forms.py
alyx/buffalo/utils.py
alyx/buffalo/views.py
alyx/templates/buffalo/electrode_bulk_load.html

Added additional field for structure name

Added additional field for structure name

---

alyx/buffalo/models.py

Fix stlfile str when a subject is deleted

Fixed deleted user name problem

---

alyx/alyx/settings.py
alyx/buffalo/admin.py
alyx/buffalo/forms.py
alyx/buffalo/models.py
alyx/buffalo/tests/test_stl_upload.py
alyx/buffalo/tests/test_trimesh.py
alyx/buffalo/utils.py
alyx/buffalo/views.py
alyx/templates/buffalo/electrode_bulk_load.html
alyx/templates/buffalo/plots.html
requirements.txt

Add electrodelogs updates

---

alyx/buffalo/admin.py

Add the subject in the inline forms in the electrode settings screen.

Fixed subject in starting points

---

alyx/alyx/settings.py

Add casting to get env var debug.

Add bool casting

---

alyx/buffalo/models.py

This PR fix a bug related to the turns and a calculated value.

Fixed turns and starting points

---

alyx/buffalo/admin.py

This PR fix a bug related to Weight.

Fixed None bug

---

alyx/buffalo/admin.py

This PR fix a session bug for weight

Fixed bug in session

---

alyx/buffalo/models.py
alyx/buffalo/views.py

This PR improve the performance in the channel recording excel load.

Improved performance

---

alyx/buffalo/admin.py
alyx/buffalo/tests/test_electrodelogs_bulk_load_tests.py
alyx/buffalo/views.py
alyx/templates/admin/change_list.html

See sessions button added to Subject Session dropdown

Electrolog and Sessions builk optimized.

---

alyx/buffalo/admin.py

This PR fix the order of the electrodelogs in the creation form.

Fix order in electrodelogs

---

alyx/buffalo/utils.py
alyx/buffalo/views.py

This PR updated session excel loads:
* Don't save: "mid-day break", "done, home" tasks
* Add cortex platform to task with .sav sufix.

Updated session load

---

alyx/buffalo/models.py
alyx/buffalo/views.py
alyx/templates/buffalo/change_form.html

This PR fix issues related to multiple clicks in the save button creating sessions.

Fix multiple clicks saving sessions

---

alyx/buffalo/models.py

Fix update session

---

alyx/alyx/settings_lab.py
alyx/buffalo/admin.py
alyx/buffalo/forms.py
alyx/buffalo/tests/test_electrodelogs_bulk_load_tests.py
alyx/buffalo/tests/tests.py
alyx/buffalo/utils.py

This PR disable delete option from device management (high rick of lost data) and add an admin for that.
Add a validation for .mat electrodes file.

Upload validations

---

alyx/buffalo/views.py

This PR fix a bug when the moneky don't have any data in the status plot.

Fixed plot bug

---

alyx/buffalo/utils.py
alyx/buffalo/views.py

This PR add labels for electrode status

Labels electrode status

---

alyx/buffalo/views.py

This PR improve the speed of the status electrode plot.

Improved query speed

---

cookbook/python/db_connection.py
cookbook/python/recipe_example.py

This PR add of a recipe from python

Added python example

---

alyx/buffalo/forms.py

This PR removes the stl field in the electrodelog visualization

Removed stl field from vis

---

alyx/buffalo/forms.py

This PR fixes a validation error for dramatiq tasks when It try to upload a channel record file.

Fix validation error

---

alyx/buffalo/admin.py
alyx/buffalo/forms.py

This PR update the some texts in the forms of electrode upload stuff.

Texts updated

---

server/docker-compose-prod.yml

This PR add a new docker-compose.yml for prod environment.

More config

---

alyx/buffalo/admin.py
alyx/templates/buffalo/admin_session_details.html
alyx/templates/buffalo/change_form.html

Tasks startime field

---

server/docker-compose-prod.yml

This PR update the docker-compose.yml for production.

docker-compose updated

---

alyx/buffalo/constants.py
alyx/buffalo/forms.py
alyx/buffalo/urls.py
alyx/buffalo/utils.py
alyx/buffalo/views.py
alyx/templates/admin/change_form.html
alyx/templates/buffalo/channelrecording_bulk_load.html
alyx/templates/buffalo/electrodelog_bulk_load.html
alyx/templates/buffalo/sessions_load.html
alyx/templates/buffalo/tasks_load.html

- Label with monkeys name for each upload form
- Typo in "Menstration" fixed
- Added error message and help text to indicate the expected date format in tasks plot

Changes requested by Ian

---

alyx/buffalo/admin.py
alyx/templates/buffalo/channelrecording_bulk_load.html
alyx/templates/buffalo/electrodelog_bulk_load.html

Change in "electrodes" drop down: left option "Upload Electrode Depth Log", right option "Upload Cell Tracking Log"

Change in buttons names
